server:
  port: 8080

spring:
  application:
    name: nexum

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Conexão com o banco
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/nexum_db}
    username: ${DATABASE_USERNAME:nexum_user}
    password: ${DATABASE_PASSWORD:nexum_password}
    driver-class-name: org.postgresql.Driver

  # Hibernate
  jpa:
    hibernate:
      ddl-auto: validate #Flyway
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}

  # Conexão com o Redis (cache)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Conexão com o kafka (eventos)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: nexum-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springdoc: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL:noreply@seudominio.com}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  seeder:
    enabled: ${SEEDER_ENABLED:true}